//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugDetail
    {
        public int PrescriptionID { get; set; }
        public int DrugID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UserGuide { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
