//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalExaminationCardDetail
    {
        public int MedicalExaminationCardID { get; set; }
        public int DoctorID { get; set; }
        public string Symptom { get; set; }
        public string Diagnosis { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual MedicalExaminationCard MedicalExaminationCard { get; set; }
    }
}
