//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalExaminationCard
    {
        public int ID { get; set; }
        public Nullable<int> Num { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string Symptom { get; set; }
        public string Diagnosis { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> NurseID { get; set; }
    
        public virtual Nurse Nurse { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
